--AQUI SE CREAN LAS TABLAS DE CADA OBJETOSS QUE HEMOS CREADO.
    CREATE TABLE ALUMNOS OF AlumnoOBJ;
    CREATE TABLE PROFESOR OF ProfesorOBJ;
    CREATE TABLE DIRECTOR OF DirectorOBJ;
    CREATE TABLE PERSONA OF PersonaOBJ;
   -- DROP TABLE PERSONA;
--INSERTS DE ALUMNOS
    INSERT INTO ALUMNOS VALUES('77669834F','Lujan',24,'NO','Jose','MEDAC Aurora',A_NOTAS(7,8,9,6),A_ASIGNATURAS('PHP','ANDROID'));
    INSERT INTO ALUMNOS VALUES('77674981G','MATHIAS',21,'SI','Sofia','MEDAC NOVA',A_NOTAS(8,6,4,9),A_ASIGNATURAS('ANDROID','LENGUAJE DE MARCAS'));
    INSERT INTO ALUMNOS VALUES('10923846U','Marta',20,'NO','Paco','MEDAC SAN RAFAEL',A_NOTAS(5,7,7,6),A_ASIGNATURAS('SWIFT','PHP'));
--INSERTS DE PROFESOR
    INSERT INTO PROFESOR VALUES('44219854O','Jose',44,'2DAM',7,'MEDAC Aurora',A_ASIGNATURA_IMPARTE('SWIFT','PHP'));
    INSERT INTO PROFESOR VALUES('09418345J','Paco',39,'1-DAW',5,'MEDAC SAN RAFAEL',A_ASIGNATURA_IMPARTE('ANDROID','LENGUAJE DE MARCAS'));
    INSERT INTO PROFESOR VALUES('99438876P','Sofia',55,'1-DAM',9,'MEDAC NOVA',A_ASIGNATURA_IMPARTE('PHP','ANDROID'));
--INSERTS DE DIRECTORES(PUEDE EXISTIR VARIOS DIRECTORES DE CADA NIVEL ACADEMICO'ESO,BACHILLER,FP.....')
    INSERT INTO DIRECTOR VALUES('11210098L','Jose David',60,'MEDAC SAN RAFAEL','FP INFORMATICA Y RRPP',1400.24);
    INSERT INTO DIRECTOR VALUES('64539628N','Lucas',33,'MEDAC Aurora','FP INFORMATICA Y RRPP',1300.24);
    INSERT INTO DIRECTOR VALUES('64539628N','Rafael',33,'MEDAC NOVA','FP INFORMATICA Y RRPP',1300.24);
    
    
    --PROCEDIMIENTO DE INSERCION DE DATOS
            --insertamos datos de profesor:
            BEGIN
                INSERTARPROFESOR('66831293T','Alfonso',58,'MEDAC Sevilla',A_ASIGNATURA_IMPARTE('GO','TYPESCRIPT'));
                INSERTARPROFESOR('94179460A','Maria Fernadez',29,'MEDAC NOVA',A_ASIGNATURA_IMPARTE('PYTHON','JAVA'));
                INSERTARPROFESOR('36029991P','Jaime ANT',38,'MEDAC NOVA',A_ASIGNATURA_IMPARTE('JAVASCRIPT','JAVA'));
                INSERTARPROFESOR('75692975K','Sanchez Sara',31,'MEDAC AURORA',A_ASIGNATURA_IMPARTE('ODOO','SWIFT'));
            END;
                SELECT*FROM PROFESOR;
                --- INSERTAMOS AHORA VALORES PARA EL DIRECTOR :)
            BEGIN
                INSERTARDIRECTOR('50864711G','Andrea',60,'MEDAC AURORA',1700);
                INSERTARDIRECTOR('62329056E','Sofian',55,'MEDAC SAN RAFAEL',1400);
                INSERTARDIRECTOR('71022330D','Lujan F',65,'MEDAC NOVA',1330);
            END;    
            SELECT*FROM DIRECTOR;
        --- INSERTAMOS  DATOS DE ALUMNOS
            BEGIN
                INSERTARALUMNOS('00610400A','IKER R.',20,'NO','Jose','MEDAC Aurora',A_NOTAS(7,7,7,6),A_ASIGNATURAS('SWIFT','TYPESCRIPT'));
                INSERTARALUMNOS('30083382A','MIGUEL F.F',19,'NO','Sofia','MEDAC NOVA',A_NOTAS(8,5,8,6),A_ASIGNATURAS('SWIFT','ANDROID'));
                INSERTARALUMNOS('07515509Y','ANA MARTINEZ',21,'NO','Jose','MEDAC Aurora',A_NOTAS(9,9,8,8),A_ASIGNATURAS('SWIFT','ANDROID'));
            END;
            SELECT*FROM ALUMNOS;
            ---------------------------------PROCEDIMIENTO DE ELIMINACION--------------------------------------------
            
    ---ELIMINAREMOS UNA TABLA DE ALUMNO 
            BEGIN
                ELIMINARALUMNOS('07515509Y'); --DEMOSTRACION DE QUE HA SIDO ELIMINADO CORRECTAMENTE
            END;
            SELECT *FROM ALUMNOS;
            --- ELIMINAREMOS UN PROFESOR -->
            BEGIN
                ELIMINARPROFESOR('66831293T'); --HEMOS ELIMINADO A UN PROFESOR
            END;
            SELECT*fROM PROFESOR;
            
                        --ELIMINAREMOS A UN DIRECTOR
            BEGIN
                ELIMINARDIRECTOR('62329056E');
            END;
------------------------------------------------PROCEDIMIENTO UPDATE-----------------------------------------------
        ---ACTUALIZAMOS UN ALUMNO
            BEGIN
                ACTUALIZARALUMNO('10923846U','Marta Martinez',21,'NO','Paco','MEDAC SAN RAFAEL',A_NOTAS(6,7,7,7),A_ASIGNATURAS('SWIFT','PHP'));
            END;
            SELECT*FROM ALUMNOS;
            
            --ACTUALIZAREMOS A UN PROFE
            BEGIN
                ACTUALIZARPROFESOR('36029991P','Jaime ANT',38,'1-DAM',9,'MEDAC NOVA',A_ASIGNATURA_IMPARTE('JAVASCRIPT','JAVA'));
                ACTUALIZARPROFESOR('94179460A','Maria Fernadez',30,'2-DAM',7,'MEDAC NOVA',A_ASIGNATURA_IMPARTE('PHP','SWIFT'));
            END;
            SELECT*FROM PROFESOR;
            
            --ACTUALIZAMOS DIRECTOR
            BEGIN
                 ACTUALIZARDIRECTOR('50864711G','Andrea',56,'MEDAC AURORA','FP DUAL TECO Y TAFAR',1800);
            END;
               SELECT*FROM DIRECTOR;       